title: <p align="center"> Poorna Chandrika Nolli </p>
logo: /assets/img/Poorna Chandrika.jpeg

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/poorna-chandrika-nolli-281609254/">LinkedIn</a> |
  <a href="https://github.com/PoornaChandrikaNolli">GitHub</a>
  
  <br>   
  I'm working on Software Development in Zeta.
  <br>
  </p>



theme: jekyll-theme-minimal
